name: Rica
favicon: null
layout_spectrum: 0.9280091400723904
typography_spectrum: 0.16409353422932327
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.8524283855222166
  lightness: 0.12351676658727229
  saturation: 0.023161915130913258
  rhythmicContrast: 0.38490786287002265
purpose: []
