typography_spectrum: 0.16409353422932327
color:
  brandColors:
    - '#f6fbfe'
    - '#060608'
    - '#e9343e'
    - '#b6b4a9'
    - '#c28464'
  brandStrength: 0.8524283855222166
  lightness: 0.12351676658727229
  saturation: 0.625
  rhythmicContrast: 0.38490786287002265
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.24861
analytics:
  google: null
  facebook: null
  twitter: null
name: Rica
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Facebook
    url: 'https://www.facebook.com/rica.estrada.9'
    type: external
favicon: null
title: Love of my life
description: The magical girl
purpose: []
